# The Travis-CI configuration for colabtools is just a stub; tests for
# colabtools are run internally.

language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

matrix:
  allow_failures:
    - python: "3.7-dev"

notifications:
  recipients:
    - colaboratory-team+travis-ci@google.com

install: pip install tox-travis
script: tox
